"""add sequence_number to quotes for stable tie-break ordering

Revision ID: 20260819_0900
Revises: 20260810_1300
Create Date: 2026-08-19 09:00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260819_0900"
down_revision: str | None = "20260810_1300"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # GENERATED BY DEFAULT AS IDENTITY tự gán giá trị tăng dần cho các dòng
    # đã có sẵn trong bảng (theo thứ tự lưu trữ vật lý, khớp thứ tự tạo với
    # các bảng chưa từng UPDATE/VACUUM FULL xáo trộn) — dùng làm tie-breaker
    # duy nhất phản ánh đúng thứ tự tạo Quote, kể cả khi nhiều Quote được tạo
    # trong cùng 1 transaction (lúc đó `created_at` giống hệt nhau).
    op.add_column(
        "quotes",
        sa.Column(
            "sequence_number",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            unique=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("quotes", "sequence_number")
